# Generated by Django 2.2.5 on 2019-10-22 00:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=15)),
                ('prod_min', models.IntegerField()),
                ('prod_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contrato', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=15)),
                ('a_paterno', models.CharField(max_length=15)),
                ('a_materno', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('MASC', 'Masculino'), ('FEME', 'Femenino')], max_length=4)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProdAlmacen.Area')),
                ('tipo_contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppProdAlmacen.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Productividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProdAlmacen.Empleado')),
            ],
        ),
    ]
